- name: configure ec2-instances and update route53 records
  hosts: local
  connection: local

# creating variables 
  vars:
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-0a2cc58738c1fdf51
    zone_id: "Z043346914G8XVEOOX7JH"
    domain_name: "msgd.fun"
    instances:
    - mongodb

# create tasks
  tasks:
  - name: create ec2-instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      tags:
        Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output

  - name: print the ec2_output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"

  # create r53 records
  - name: create route53 record 
    amazon.aws.route53:
      state: present
      zone: "{{ zone_id }}"
      record: "{{ item.item }}.{{ domain_name }}"
      type: A
      ttl: 1
      value: "{{ item.instance[0].private_ip_address }}"
      overwrite: true
    loop:
    - "{{ ec2_output.results }}"

