- name: create ec2-user and also r53 record
  hosts: local
  connection: local

# create variables
  vars:
   ami_id: "ami-09c813fb71547fc4f"
   sg: "sg-0791170cc74d2baac"
   domain_name: "msgd.fun"
   zone_id: "Z043346914G8XVEOOX7JH"

  # create task

  tasks:
  - name: create ec2-instances
    amazon.aws.ec2_instance:
      name: {{ item }}
      instance_type: "t3.micro"
      image_id: {{ ami_id }}
      region: us-east-1
      security_group: {{ sg }}
      tags: 
        Name: {{ item }}
    loop: {{ instances }}