- name: setup catalogue server
  hosts: catalogue
  become: yes

# create catalogue tasks

  tasks:

  - name: disable nodejs
    ansible.builtin.command: dnf module disable nodejs -y
   
  - name: enable nodejs:20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: create system user
    ansible.builtin.user:
      name: roboshop
      comment: RoboShop System user
      system: true
      shell: /sbin/nologin
      home: /app

# Safe to remove directory, because 2nd time if we run it will download freshly. no error if does not exist
  
  - name: remove app directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: remove app directory
    ansible.builtin.file:
      path: /app
      state: present

  - name: Delete catalogue file
    ansible.builtin.file:
      path: /tmp/catalogue.zip
      state: absent
      
  - name: Download the file
    ansible.builtin.get_url:
      url: curl -o /tmp/catalogue.zip https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip 
      dest: /app

  - name: Unarchive a file 
    ansible.builtin.unarchive:
      src:  https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip 
      dest: /tmp/catalogue.zip
      remote_src: yes
    args:
      chdir: /app
  
  - name: Install npm package.
    community.general.npm:
      path: /app

  - name: copy cagtalogue.serivce file 
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: copy mongo.repo file 
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: Install mongodb-mongosh
    ansible.builtin.package:
      name: mongodb-mongosh
      state: present
  
  - name: connnect to mongodb catalogue
    ansible.builtin.command: mongosh mongodb.msgd.fun --quiet --eval "db.getMongo().getDBNames().indexOf('catalogue')"
    register: catalogue_output

  - name: load mongodb data
    ansible.builtin.command: mongosh --host mongodb.msgd.fun </app/db/master-data.js
    when: catalogue_output.stdout | int < 0

  - name: daemon reload enable and start
    ansible.builtin.systemd_service:
      name: catalogue
      enabled: true
      state: started
      daemon_reload: true

  
