- name: mongodb configure
  hosts: mongodb
  become: yes

  vars:
    MONGODB_HOST: mongodb.msgd.fun
  
  tasks:
  - name: copy repo file 
    ansible.builtin.copy:
      src: ./mongo.repo
      dest: /etc/yum.repos.d/mongo.repo
      # remote_src : true

  # install monogdb
  - name: install mongodb
    ansible.builtin.dnf:
      name: mongodb-org 
      state: present

  # Update listen address from 127.0.0.1 to 0.0.0.0 in /etc/mongod.conf
  - name: Update listen address from 127.0.0.1 to 0.0.0.0 in /etc/mongod.conf
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  # systemctl restart mongodb
  - name: systemctl restart mongodb
    ansible.builtin.service:
      state: restarted
      name: mongod
      enabled: yes
  